// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExamenCertifac.Models;

public partial class Addendas
{
    [Key]
    public Guid IdAddenda { get; set; }

    [StringLength(50)]
    public string NombreAddenda { get; set; }

    public string XML { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? FechaModificacion { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Usuario { get; set; }

    public bool? Estado { get; set; }
}