// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExamenCertifac.Models;

[Index("Name", Name = "RoleNameIndex", IsUnique = true)]
public partial class AspNetRoles
{
    [Key]
    [StringLength(128)]
    public string Id { get; set; }

    [Required]
    [StringLength(256)]
    public string Name { get; set; }

    [ForeignKey("RoleId")]
    [InverseProperty("Role")]
    public virtual ICollection<AspNetUsers> User { get; set; } = new List<AspNetUsers>();
}